---
Name: Background
Mesh: unitsquare
Material: background
Transform:
    Position: !Vector3 0 0 -149
    Scale: !Vector3 150 85 1
    Rotation: !Vector3 0 0 0
---
Name: DirLight
Light: !Light-Directional
    Color: !Vector3 1 1 1
    Direction: !Vector3 -.3 -.7 -1