---
Name: Grid
Grid:
    Rows: 8
    Cols: 8
Transform:
    Position: !Vector3 -15.75 15.66 -50
    Rotation: !Vector3 90 0 0
---
Name: Background
Mesh: unitsquare
Material: background
Transform:
    Position: !Vector3 0 0 -149
    Scale: !Vector3 150 85 1
    Rotation: !Vector3 0 0 0
---
Name: DirLight
DirectionalLight:
    Color: !Vector3 1 1 1
    Direction: !Vector3 -1
     -1 -.7