Logging:
    Debug:
        OutputVerbosity: !Verbosity Debug
        LoggingVerbosity: !Verbosity Debug
    Release:
        OutputVerbosity: !Verbosity Medium
        OutputVerbosity: !Verbosity Medium
Display:
    Fullscreen: false
    Height: 720
    Width: 1280
Graphics:
    BackfaceCulling: true
    VSync: false