Up:
    Keyboard: Up
Right:
    Keyboard: Right
Down:
    Keyboard: Down
Left:
    Keyboard: Left
Space:
    Keyboard: Space
Select:
    Mouse: Left
Toggle1:
    Keyboard: M
Exit:
    Keyboard: Delete